repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false
  default_branch: main

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      required_status_checks:
        strict: true
        contexts:
          - "test"
      enforce_admins: false  # Allows admins to bypass restrictions
      restrictions: null  # Anyone with write access can create branches
      allow_force_pushes: false
      allow_deletions: false